stages:          # List of stages for jobs, and their order of execution
  - compile
  - sonarqube-analysis
  - build
  - deploy

compile-job:       # This job runs in the build stage, which runs first.
  stage: compile
  tags:
    - "self-hosted"
  script:
    - echo "Compiling the code..."
    - mvn clean compile

sonarqube-job:   # This job runs in the test stage.
  stage: sonarqube-analysis    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running Sonarqube Analysis"
    - mvn sonar:sonar -Dsonar.host.url=http://3.110.108.214:9000/ -Dsonar.login=squ_6be8ca69f560673e3ff0efcdaa621a314e4a94b2 -Dsonar.projectKey=myproject -Dsonar.projectName=Petclinic -Dsonar.java.binaries=.

build-job:   # This job also runs in the test stage.
  stage: build
  tags:
    - "self-hosted"    # It can run at the same time as unit-test-job (in parallel).
  script:
    - echo "Maven Build"
    - mvn clean install

deploy-job:      # This job runs in the deploy stage.
  stage: deploy
  tags:
    - "self-hosted"  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "Deploying application..."
    - docker build -t pet1 -t adijaiswal/pet1:latest .
    - echo $DOCKER_PASS | docker login -u adijaiswal --password-stdin
    - docker push adijaiswal/pet1:latest

