stages:          # List of stages for jobs, and their order of execution
  - compile
  - sonarqube-analysis
  - build
  - deploy


deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - sudo cp /home/gitlab-runner/builds/A-TsRgKM/0/jaiswaladi246/petclinic/target/petclinic.war /opt/apache-tomcat-9.0.65/webapps/
